function OnEnter()
	if(LuaQueryPersonInMap("lu_fb1")==0)then--if副本内无人则重置数据
	LuaPublicDel("fbdata/fb01/jg1")--重置所有机关off
	LuaPublicDel("fbdata/fb01/jg2")
	LuaPublicDel("fbdata/fb01/jg3")
	LuaPublicDel("fbdata/fb01/jg4")
	--LuaPublicDel("fbdata/fb01/jg5")--暂无开关
	--LuaPublicDel("fbdata/fb01/jg6")
	--LuaPublicDel("fbdata/fb01/jg7")
	--LuaPublicDel("fbdata/fb01/jg8")
	--LuaPublicDel("fbdata/fb01/jg9")
	LuaPublicDel("fbdata/fb01/m1")--重置所有怪物on
	LuaPublicDel("fbdata/fb01/m2")
	LuaPublicDel("fbdata/fb01/m3")
	LuaPublicDel("fbdata/fb01/m4")
	LuaPublicDel("fbdata/fb01/e1")--清装备无
	LuaPublicDel("fbdata/fb01/e2")
	LuaPublicDel("fbdata/fb01/e3")
	LuaPublicDel("fbdata/fb01/rollmax")--temp
	LuaPublicDel("fbdata/fb01/rollmax1")--全队最大ROLL点
	LuaPublicDel("fbdata/fb01/rollmax2")
	LuaPublicDel("fbdata/fb01/rollmax3")
	LuaPublicDel("fbdata/fb01/r1")--全队ROLL点
	LuaPublicDel("fbdata/fb01/r2")
	LuaPublicDel("fbdata/fb01/r3")
	LuaPublicDel("fbdata/fb01/r4")
	LuaPublicDel("fbdata/fb01/r5")
	LuaPublicDel("fbdata/fb01/r21")--BOSS2全队ROLL点防止不按123顺序打BOSS掷点混乱
	LuaPublicDel("fbdata/fb01/r22")
	LuaPublicDel("fbdata/fb01/r23")
	LuaPublicDel("fbdata/fb01/r24")
	LuaPublicDel("fbdata/fb01/r25")
	LuaPublicDel("fbdata/fb01/r31")--BOSS3全队ROLL点防止不按123顺序打BOSS掷点混乱
	LuaPublicDel("fbdata/fb01/r32")
	LuaPublicDel("fbdata/fb01/r33")
	LuaPublicDel("fbdata/fb01/r34")
	LuaPublicDel("fbdata/fb01/r35")
	LuaPublicDel("fbdata/fb01/kb1")--killboss1状态0,1已杀,2ROLL完
	LuaPublicDel("fbdata/fb01/kb2")
	LuaPublicDel("fbdata/fb01/kb3")
	LuaPublicDel("fbdata/fb01/rt1")--开roll时间0
	LuaPublicDel("fbdata/fb01/rt2")
	LuaPublicDel("fbdata/fb01/rt3")
	LuaPublicDel("fbdata/fb01/p1")--已roll点人数
	LuaPublicDel("fbdata/fb01/p2")
	LuaPublicDel("fbdata/fb01/p3")
	LuaDelTask("fb01r1")--BOSS1ROLL值
	LuaDelTask("fb01r2")
	LuaDelTask("fb01r3")
	--msg2team("副本已重置")
	end
--LuaOtherSendMenu()
return 1
end